### ISSUE TITLE
Erreur build

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#766]
```
julien@CM57-DEL12:~/dodocgit/dodoc10/client$ npm run build

> app@0.1.0 build
> vue-cli-service build

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠦  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
⠙  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
⠹  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
⠋  Building for production...

 ERROR  Failed to compile with 1 error                                                                                                                                                              23:15:26


/home/julien/dodocgit/dodoc10/client/src/components/makes/TrimAudioVideo.vue
  29:38  error  Parsing error: duplicate-attribute  vue/no-parsing-error
  29:38  error  Duplicate attribute 'class'         vue/no-duplicate-attributes

✖ 2 problems (2 errors, 0 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/bundle.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/875.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/2.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/984.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/363.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/421.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/33.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/403.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/599.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/678.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/248.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/127.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/ProjectView.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/871.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/HomeView.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/126.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/SpaceView.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/979.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/PublicationView.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/AuthorView.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/28.js": no such file
Error parsing bundle asset "/home/julien/dodocgit/dodoc10/client/dist/js/153.js": no such file

No bundles were parsed. Analyzer will show only original module sizes from stats file.

Webpack Bundle Analyzer saved report to /home/julien/dodocgit/dodoc10/client/dist/report.html
 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /home/julien/dodocgit/dodoc10/client/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /home/julien/dodocgit/dodoc10/client/node_modules/webpack/lib/webpack.js:148:8
    at /home/julien/dodocgit/dodoc10/client/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/julien/dodocgit/dodoc10/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/julien/dodocgit/dodoc10/client/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/home/julien/dodocgit/dodoc10/client/node_modules/webpack/lib/Cache.js:150:23)
    at /home/julien/dodocgit/dodoc10/client/node_modules/webpack/lib/Compiler.js:1212:15
    at Hook.eval [as callAsync] (eval at create (/home/julien/dodocgit/dodoc10/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/julien/dodocgit/dodoc10/client/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/home/julien/dodocgit/dodoc10/client/node_modules/webpack/lib/Compiler.js:1205:23)
    at /home/julien/dodocgit/dodoc10/client/node_modules/webpack/lib/webpack.js:147:16
    at finalCallback (/home/julien/dodocgit/dodoc10/client/node_modules/webpack/lib/Compiler.js:441:32)
    at /home/julien/dodocgit/dodoc10/client/node_modules/webpack/lib/Compiler.js:458:13
    at eval (eval at create (/home/julien/dodocgit/dodoc10/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:29:1)
    at Immediate.<anonymous> (/home/julien/dodocgit/dodoc10/client/node_modules/webpack-bundle-analyzer/lib/BundleAnalyzerPlugin.js:74:13)
    at runMicrotasks (<anonymous>)
```

**Comment by jubonhomme** [comment]
Fix
