### ISSUE TITLE
Bug lancement dodoc

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#853]
```
> dodoc@10.0.6-dev start
> electron .

INDEX / didn’t find override settings
SOCKETS • Sockets module initialized
App threw an error during load
Error: Cannot find module 'exiftool-vendored.pl'
Require stack:
- /home/julien/dodocgit/dodoc10/node_modules/exiftool-vendored/dist/ExifTool.js
- /home/julien/dodocgit/dodoc10/node_modules/extractd/extractd.js
- /home/julien/dodocgit/dodoc10/core2/exporter_tasks/optimizer.js
- /home/julien/dodocgit/dodoc10/core2/Exporter.js
- /home/julien/dodocgit/dodoc10/core2/api2.js
- /home/julien/dodocgit/dodoc10/core2/server.js
- /home/julien/dodocgit/dodoc10/core2/main2.js
- /home/julien/dodocgit/dodoc10/index.js
- /home/julien/dodocgit/dodoc10/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at findExiftool (/home/julien/dodocgit/dodoc10/node_modules/exiftool-vendored/dist/ExifTool.js:57:18)
    at Object.<anonymous> (/home/julien/dodocgit/dodoc10/node_modules/exiftool-vendored/dist/ExifTool.js:79:31)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/julien/dodocgit/dodoc10/node_modules/extractd/extractd.js:7:18)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'exiftool-vendored.pl'
Require stack:
- /home/julien/dodocgit/dodoc10/node_modules/exiftool-vendored/dist/ExifTool.js
- /home/julien/dodocgit/dodoc10/node_modules/extractd/extractd.js
- /home/julien/dodocgit/dodoc10/core2/exporter_tasks/optimizer.js
- /home/julien/dodocgit/dodoc10/core2/Exporter.js
- /home/julien/dodocgit/dodoc10/core2/api2.js
- /home/julien/dodocgit/dodoc10/core2/server.js
- /home/julien/dodocgit/dodoc10/core2/main2.js
- /home/julien/dodocgit/dodoc10/index.js
- /home/julien/dodocgit/dodoc10/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at findExiftool (/home/julien/dodocgit/dodoc10/node_modules/exiftool-vendored/dist/ExifTool.js:57:18)
    at Object.<anonymous> (/home/julien/dodocgit/dodoc10/node_modules/exiftool-vendored/dist/ExifTool.js:79:31)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/julien/dodocgit/dodoc10/node_modules/extractd/extractd.js:7:18)

```

**Comment by jubonhomme** [comment]
Je viens de voir que ça fonctionne si je n'utilise pas "npm install --no-optional" pour l'installation
Mais si je n'utilise pas ça ça plante à cause des PDF ...
Pas simple de choisir

**Comment by louis-ev** [comment]
Ça vient de la nouvelle dépendance extractd, qui utilise exiftool-vendored.

Je trouve ça concernant Linux : 

If you're installing on a minimal Linux distribution, you may need to install perl. On Alpine, run apk add perl.

**Comment by jubonhomme** [comment]
oui si je n'utilise pas l'option no --optional pour l'installation, dodoc s'ouvre bien et je peux convertir un CR2.
Par contre dès qu'il y a un pdf dans un projet ça me plante dodoc, c'est pour ça que j'utilisais  "npm install --no-optional" pour l'installation

**Comment by louis-ev** [comment]
Effectivement, il y a des dépendances optionnelles pour `exiftool-vendored`. Sacré micmac…
Dans 8babb2be8a0505f6d2ecec7b2613156a3575908f j'ai passé extractd en dépendance optionnelle.

Bon, le mieux serait qu'on résolve ces soucis de PDF / linux, y a vraiment 0 raisons que ça marche pas !

**Comment by jubonhomme** [comment]
Pour l'instant il y en a bien UNE qui fait que ça marche pas ;)
Mais si tu as une piste pour que je cherche d'où ça vient je peux regarder.
